komga:
  filesystem-scanner-force-directory-modified-time: false
  remember-me:
    key: changeMe!
    validity: 2592000 # 1 month
  #  libraries-scan-cron: "*/5 * * * * ?" #every 5 seconds
  libraries-scan-cron: "-" #disable
  libraries-scan-startup: true
  database:
    file: ":memory:"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  artemis:
    embedded:
      data-directory: ./artemis
logging:
  file:
    max-history: 1
    name: komga-dev.log
  level:
    org.apache.activemq.audit.message: WARN
#    org.jooq: DEBUG
#    web: DEBUG
    org.gotson.komga: DEBUG
#    org.springframework.jms: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG

management.metrics.export.influx:
  #  enabled: true
  uri: http://localhost:8086

springdoc:
  cache:
    disabled: true

#server:
#  servlet:
#    context-path: /komga
